<a href="https://colab.research.google.com/github/shubhkhandare/realestate-data-analysis/blob/main/BeautifulSoup_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install beautifulsoup4 lxml

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (6.1.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
import requests

In [ ]:
respose = requests.get("https://scrapifydatalabs.com/playground/nestly/")

In [ ]:
print(respose)

<Response [200]>

In [ ]:
soup = BeautifulSoup(respose.text, "html.parser")

In [ ]:
print(soup.title.text)

Nestly Home Search — Zillow-style Real Estate Scraping Practice | Scrapify

In [ ]:
home = soup.find("div", id="nl-home-list")

In [ ]:
print(home)

[<div id="nl-home-list">
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="6" data-hoa="0" data-home-id="nl-1001" data-lat="30.209" data-lng="-97.797" data-price="625000" data-sqft="1680" data-status="for_sale" data-type="Single Family" data-zip="78745">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="625000" data-price-display="$625,000">$625,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1680">1,680</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1001">1842 Maple Ridge Dr, Austin, TX 78745</a></p>
<div class="nl-meta"><span data-days-on-nestly="6">6 days on Nestly</span></div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="2" data-city="Austin" data-days="12" data-hoa="385" data-home-id="nl-1002" data-lat="30.265" data-lng="-97.753" data-price="419000" data-sqft="1045" data-status="for_sale" data-type="Condo" data-zip="78701">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Condo for sale">Condo for sale</span>
              🏢
            </div>
<div>
<p class="nl-price" data-price="419000" data-price-display="$419,000">$419,000</p>
<p class="nl-facts"><strong data-beds="2">2</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1045">1,045</strong> sqft | <span data-home-type="Condo">Condo</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1002">900 W Cesar Chavez St #412, Austin, TX 78701</a></p>
<div class="nl-meta"><span data-days-on-nestly="12">12 days on Nestly</span> · HOA $385/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>
<article class="nl-card" data-baths="3" data-beds="4" data-city="Austin" data-days="21" data-hoa="45" data-home-id="nl-1003" data-lat="30.342" data-lng="-97.762" data-price="875000" data-sqft="2450" data-status="pending" data-type="Single Family" data-zip="78731">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge pending" data-badge="Pending">Pending</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="875000" data-price-display="$875,000">$875,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="3">3</strong> ba | <strong data-sqft="2450">2,450</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1003">4110 Lakewood Cove, Austin, TX 78731</a></p>
<div class="nl-meta"><span data-days-on-nestly="21">21 days on Nestly</span> · HOA $45/mo</div>
<div class="nl-broker" data-agent="Ava Chen" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>
<article class="nl-card" data-baths="2.5" data-beds="3" data-city="Austin" data-days="4" data-hoa="210" data-home-id="nl-1004" data-lat="30.298" data-lng="-97.704" data-price="512000" data-sqft="1720" data-status="for_sale" data-type="Townhouse" data-zip="78723">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Townhouse for sale">Townhouse for sale</span>
              🏘️
            </div>
<div>
<p class="nl-price" data-price="512000" data-price-display="$512,000">$512,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2.5">2.5</strong> ba | <strong data-sqft="1720">1,720</strong> sqft | <span data-home-type="Townhouse">Townhouse</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1004">128 Mueller Blvd, Austin, TX 78723</a></p>
<div class="nl-meta"><span data-days-on-nestly="4">4 days on Nestly</span> · HOA $210/mo</div>
<div class="nl-broker" data-agent="Riley Nguyen" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>
<article class="nl-card" data-baths="4" data-beds="5" data-city="Austin" data-days="18" data-hoa="0" data-home-id="nl-1005" data-lat="30.248" data-lng="-97.785" data-price="1149000" data-sqft="3210" data-status="for_sale" data-type="Single Family" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="1149000" data-price-display="$1,149,000">$1,149,000</p>
<p class="nl-facts"><strong data-beds="5">5</strong> bds | <strong data-baths="4">4</strong> ba | <strong data-sqft="3210">3,210</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1005">55 Barton Hills Dr, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="18">18 days on Nestly</span></div>
<div class="nl-broker" data-agent="Morgan Lee" data-broker="South Austin Estates">South Austin Estates</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="2" data-city="Austin" data-days="3" data-hoa="0" data-home-id="nl-1006" data-lat="30.402" data-lng="-97.725" data-price="2450" data-sqft="980" data-status="for_rent" data-type="Apartment" data-zip="78758">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge" data-badge="Apartment for rent">Apartment for rent</span>
              🏬
            </div>
<div>
<p class="nl-price" data-price="2450" data-price-display="$2,450/mo">$2,450/mo</p>
<p class="nl-facts"><strong data-beds="2">2</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="980">980</strong> sqft | <span data-home-type="Apartment">Apartment</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1006">2100 Domain Dr #221, Austin, TX 78758</a></p>
<div class="nl-meta"><span data-days-on-nestly="3">3 days on Nestly</span></div>
<div class="nl-broker" data-agent="Nestly Rentals" data-broker="Nestly Property Mgmt">Nestly Property Mgmt</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="31" data-hoa="0" data-home-id="nl-1007" data-lat="30.271" data-lng="-97.685" data-price="389000" data-sqft="1410" data-status="for_sale" data-type="Single Family" data-zip="78721">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="389000" data-price-display="$389,000">$389,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1410">1,410</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1007">902 Delano St, Austin, TX 78721</a></p>
<div class="nl-meta"><span data-days-on-nestly="31">31 days on Nestly</span></div>
<div class="nl-broker" data-agent="Chris Park" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>
<article class="nl-card" data-baths="1" data-beds="1" data-city="Austin" data-days="9" data-hoa="295" data-home-id="nl-1008" data-lat="30.263" data-lng="-97.768" data-price="299000" data-sqft="712" data-status="for_sale" data-type="Condo" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Condo for sale">Condo for sale</span>
              🏢
            </div>
<div>
<p class="nl-price" data-price="299000" data-price-display="$299,000">$299,000</p>
<p class="nl-facts"><strong data-beds="1">1</strong> bds | <strong data-baths="1">1</strong> ba | <strong data-sqft="712">712</strong> sqft | <span data-home-type="Condo">Condo</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1008">1800 Barton Springs Rd #7, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="9">9 days on Nestly</span> · HOA $295/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>
<article class="nl-card" data-baths="3" data-beds="4" data-city="Austin" data-days="15" data-hoa="55" data-home-id="nl-1009" data-lat="30.252" data-lng="-97.845" data-price="749000" data-sqft="2288" data-status="for_sale" data-type="Single Family" data-zip="78735">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="749000" data-price-display="$749,000">$749,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="3">3</strong> ba | <strong data-sqft="2288">2,288</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1009">3311 Scenic Brook Dr, Austin, TX 78735</a></p>
<div class="nl-meta"><span data-days-on-nestly="15">15 days on Nestly</span> · HOA $55/mo</div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="27" data-hoa="0" data-home-id="nl-1010" data-lat="30.312" data-lng="-97.723" data-price="535000" data-sqft="1595" data-status="pending" data-type="Single Family" data-zip="78751">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge pending" data-badge="Pending">Pending</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="535000" data-price-display="$535,000">$535,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1595">1,595</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1010">4702 Duval St, Austin, TX 78751</a></p>
<div class="nl-meta"><span data-days-on-nestly="27">27 days on Nestly</span></div>
<div class="nl-broker" data-agent="Ava Chen" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="2" data-hoa="0" data-home-id="nl-1011" data-lat="30.269" data-lng="-97.722" data-price="3200" data-sqft="1500" data-status="for_rent" data-type="Single Family" data-zip="78702">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge" data-badge="House for rent">House for rent</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="3200" data-price-display="$3,200/mo">$3,200/mo</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1500">1,500</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1011">1204 E 12th St, Austin, TX 78702</a></p>
<div class="nl-meta"><span data-days-on-nestly="2">2 days on Nestly</span></div>
<div class="nl-broker" data-agent="Nestly Rentals" data-broker="Nestly Property Mgmt">Nestly Property Mgmt</div>
</div>
</article>
<article class="nl-card" data-baths="4" data-beds="6" data-city="Austin" data-days="40" data-hoa="0" data-home-id="nl-1012" data-lat="30.255" data-lng="-97.719" data-price="895000" data-sqft="2800" data-status="for_sale" data-type="Multi Family" data-zip="78702">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Multi-family for sale">Multi-family for sale</span>
              🏘️
            </div>
<div>
<p class="nl-price" data-price="895000" data-price-display="$895,000">$895,000</p>
<p class="nl-facts"><strong data-beds="6">6</strong> bds | <strong data-baths="4">4</strong> ba | <strong data-sqft="2800">2,800</strong> sqft | <span data-home-type="Multi Family">Multi Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1012">2201 E Cesar Chavez St, Austin, TX 78702</a></p>
<div class="nl-meta"><span data-days-on-nestly="40">40 days on Nestly</span></div>
<div class="nl-broker" data-agent="Chris Park" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="11" data-hoa="0" data-home-id="nl-1013" data-lat="30.361" data-lng="-97.716" data-price="459000" data-sqft="1522" data-status="for_sale" data-type="Single Family" data-zip="78758">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="459000" data-price-display="$459,000">$459,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1522">1,522</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1013">8100 Research Blvd, Austin, TX 78758</a></p>
<div class="nl-meta"><span data-days-on-nestly="11">11 days on Nestly</span></div>
<div class="nl-broker" data-agent="Morgan Lee" data-broker="North Nestly Homes">North Nestly Homes</div>
</div>
</article>
<article class="nl-card" data-baths="5.5" data-beds="5" data-city="Austin" data-days="55" data-hoa="120" data-home-id="nl-1014" data-lat="30.301" data-lng="-97.795" data-price="2150000" data-sqft="4820" data-status="for_sale" data-type="Single Family" data-zip="78746">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏰
            </div>
<div>
<p class="nl-price" data-price="2150000" data-price-display="$2,150,000">$2,150,000</p>
<p class="nl-facts"><strong data-beds="5">5</strong> bds | <strong data-baths="5.5">5.5</strong> ba | <strong data-sqft="4820">4,820</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1014">18 Westlake Dr, Austin, TX 78746</a></p>
<div class="nl-meta"><span data-days-on-nestly="55">55 days on Nestly</span> · HOA $120/mo</div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="8" data-hoa="95" data-home-id="nl-1015" data-lat="30.181" data-lng="-97.741" data-price="175000" data-sqft="1210" data-status="for_sale" data-type="Manufactured" data-zip="78744">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Mobile home for sale">Mobile home for sale</span>
              🚐
            </div>
<div>
<p class="nl-price" data-price="175000" data-price-display="$175,000">$175,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1210">1,210</strong> sqft | <span data-home-type="Manufactured">Manufactured</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1015">Lot 42 Pioneer Trails, Austin, TX 78744</a></p>
<div class="nl-meta"><span data-days-on-nestly="8">8 days on Nestly</span> · HOA $95/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>
<article class="nl-card" data-baths="2" data-beds="4" data-city="Austin" data-days="14" data-hoa="0" data-home-id="nl-1016" data-lat="30.239" data-lng="-97.769" data-price="589000" data-sqft="1890" data-status="for_sale" data-type="Single Family" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="589000" data-price-display="$589,000">$589,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1890">1,890</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1016">1608 Southwood Rd, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="14">14 days on Nestly</span></div>
<div class="nl-broker" data-agent="Riley Nguyen" data-broker="South Austin Estates">South Austin Estates</div>
</div>
</article>
</div>]

In [ ]:
card = soup.find_all("article", class_="nl-card")

In [ ]:
print(card)

[<article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="6" data-hoa="0" data-home-id="nl-1001" data-lat="30.209" data-lng="-97.797" data-price="625000" data-sqft="1680" data-status="for_sale" data-type="Single Family" data-zip="78745">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="625000" data-price-display="$625,000">$625,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1680">1,680</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1001">1842 Maple Ridge Dr, Austin, TX 78745</a></p>
<div class="nl-meta"><span data-days-on-nestly="6">6 days on Nestly</span></div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="2" data-city="Austin" data-days="12" data-hoa="385" data-home-id="nl-1002" data-lat="30.265" data-lng="-97.753" data-price="419000" data-sqft="1045" data-status="for_sale" data-type="Condo" data-zip="78701">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Condo for sale">Condo for sale</span>
              🏢
            </div>
<div>
<p class="nl-price" data-price="419000" data-price-display="$419,000">$419,000</p>
<p class="nl-facts"><strong data-beds="2">2</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1045">1,045</strong> sqft | <span data-home-type="Condo">Condo</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1002">900 W Cesar Chavez St #412, Austin, TX 78701</a></p>
<div class="nl-meta"><span data-days-on-nestly="12">12 days on Nestly</span> · HOA $385/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>, <article class="nl-card" data-baths="3" data-beds="4" data-city="Austin" data-days="21" data-hoa="45" data-home-id="nl-1003" data-lat="30.342" data-lng="-97.762" data-price="875000" data-sqft="2450" data-status="pending" data-type="Single Family" data-zip="78731">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge pending" data-badge="Pending">Pending</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="875000" data-price-display="$875,000">$875,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="3">3</strong> ba | <strong data-sqft="2450">2,450</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1003">4110 Lakewood Cove, Austin, TX 78731</a></p>
<div class="nl-meta"><span data-days-on-nestly="21">21 days on Nestly</span> · HOA $45/mo</div>
<div class="nl-broker" data-agent="Ava Chen" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>, <article class="nl-card" data-baths="2.5" data-beds="3" data-city="Austin" data-days="4" data-hoa="210" data-home-id="nl-1004" data-lat="30.298" data-lng="-97.704" data-price="512000" data-sqft="1720" data-status="for_sale" data-type="Townhouse" data-zip="78723">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Townhouse for sale">Townhouse for sale</span>
              🏘️
            </div>
<div>
<p class="nl-price" data-price="512000" data-price-display="$512,000">$512,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2.5">2.5</strong> ba | <strong data-sqft="1720">1,720</strong> sqft | <span data-home-type="Townhouse">Townhouse</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1004">128 Mueller Blvd, Austin, TX 78723</a></p>
<div class="nl-meta"><span data-days-on-nestly="4">4 days on Nestly</span> · HOA $210/mo</div>
<div class="nl-broker" data-agent="Riley Nguyen" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>, <article class="nl-card" data-baths="4" data-beds="5" data-city="Austin" data-days="18" data-hoa="0" data-home-id="nl-1005" data-lat="30.248" data-lng="-97.785" data-price="1149000" data-sqft="3210" data-status="for_sale" data-type="Single Family" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="1149000" data-price-display="$1,149,000">$1,149,000</p>
<p class="nl-facts"><strong data-beds="5">5</strong> bds | <strong data-baths="4">4</strong> ba | <strong data-sqft="3210">3,210</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1005">55 Barton Hills Dr, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="18">18 days on Nestly</span></div>
<div class="nl-broker" data-agent="Morgan Lee" data-broker="South Austin Estates">South Austin Estates</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="2" data-city="Austin" data-days="3" data-hoa="0" data-home-id="nl-1006" data-lat="30.402" data-lng="-97.725" data-price="2450" data-sqft="980" data-status="for_rent" data-type="Apartment" data-zip="78758">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge" data-badge="Apartment for rent">Apartment for rent</span>
              🏬
            </div>
<div>
<p class="nl-price" data-price="2450" data-price-display="$2,450/mo">$2,450/mo</p>
<p class="nl-facts"><strong data-beds="2">2</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="980">980</strong> sqft | <span data-home-type="Apartment">Apartment</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1006">2100 Domain Dr #221, Austin, TX 78758</a></p>
<div class="nl-meta"><span data-days-on-nestly="3">3 days on Nestly</span></div>
<div class="nl-broker" data-agent="Nestly Rentals" data-broker="Nestly Property Mgmt">Nestly Property Mgmt</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="31" data-hoa="0" data-home-id="nl-1007" data-lat="30.271" data-lng="-97.685" data-price="389000" data-sqft="1410" data-status="for_sale" data-type="Single Family" data-zip="78721">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="389000" data-price-display="$389,000">$389,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1410">1,410</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1007">902 Delano St, Austin, TX 78721</a></p>
<div class="nl-meta"><span data-days-on-nestly="31">31 days on Nestly</span></div>
<div class="nl-broker" data-agent="Chris Park" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>, <article class="nl-card" data-baths="1" data-beds="1" data-city="Austin" data-days="9" data-hoa="295" data-home-id="nl-1008" data-lat="30.263" data-lng="-97.768" data-price="299000" data-sqft="712" data-status="for_sale" data-type="Condo" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Condo for sale">Condo for sale</span>
              🏢
            </div>
<div>
<p class="nl-price" data-price="299000" data-price-display="$299,000">$299,000</p>
<p class="nl-facts"><strong data-beds="1">1</strong> bds | <strong data-baths="1">1</strong> ba | <strong data-sqft="712">712</strong> sqft | <span data-home-type="Condo">Condo</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1008">1800 Barton Springs Rd #7, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="9">9 days on Nestly</span> · HOA $295/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>, <article class="nl-card" data-baths="3" data-beds="4" data-city="Austin" data-days="15" data-hoa="55" data-home-id="nl-1009" data-lat="30.252" data-lng="-97.845" data-price="749000" data-sqft="2288" data-status="for_sale" data-type="Single Family" data-zip="78735">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="749000" data-price-display="$749,000">$749,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="3">3</strong> ba | <strong data-sqft="2288">2,288</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1009">3311 Scenic Brook Dr, Austin, TX 78735</a></p>
<div class="nl-meta"><span data-days-on-nestly="15">15 days on Nestly</span> · HOA $55/mo</div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="27" data-hoa="0" data-home-id="nl-1010" data-lat="30.312" data-lng="-97.723" data-price="535000" data-sqft="1595" data-status="pending" data-type="Single Family" data-zip="78751">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge pending" data-badge="Pending">Pending</span>
              🏡
            </div>
<div>
<p class="nl-price" data-price="535000" data-price-display="$535,000">$535,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1595">1,595</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1010">4702 Duval St, Austin, TX 78751</a></p>
<div class="nl-meta"><span data-days-on-nestly="27">27 days on Nestly</span></div>
<div class="nl-broker" data-agent="Ava Chen" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="2" data-hoa="0" data-home-id="nl-1011" data-lat="30.269" data-lng="-97.722" data-price="3200" data-sqft="1500" data-status="for_rent" data-type="Single Family" data-zip="78702">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge" data-badge="House for rent">House for rent</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="3200" data-price-display="$3,200/mo">$3,200/mo</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1500">1,500</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1011">1204 E 12th St, Austin, TX 78702</a></p>
<div class="nl-meta"><span data-days-on-nestly="2">2 days on Nestly</span></div>
<div class="nl-broker" data-agent="Nestly Rentals" data-broker="Nestly Property Mgmt">Nestly Property Mgmt</div>
</div>
</article>, <article class="nl-card" data-baths="4" data-beds="6" data-city="Austin" data-days="40" data-hoa="0" data-home-id="nl-1012" data-lat="30.255" data-lng="-97.719" data-price="895000" data-sqft="2800" data-status="for_sale" data-type="Multi Family" data-zip="78702">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Multi-family for sale">Multi-family for sale</span>
              🏘️
            </div>
<div>
<p class="nl-price" data-price="895000" data-price-display="$895,000">$895,000</p>
<p class="nl-facts"><strong data-beds="6">6</strong> bds | <strong data-baths="4">4</strong> ba | <strong data-sqft="2800">2,800</strong> sqft | <span data-home-type="Multi Family">Multi Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1012">2201 E Cesar Chavez St, Austin, TX 78702</a></p>
<div class="nl-meta"><span data-days-on-nestly="40">40 days on Nestly</span></div>
<div class="nl-broker" data-agent="Chris Park" data-broker="Eastside Nestly">Eastside Nestly</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="11" data-hoa="0" data-home-id="nl-1013" data-lat="30.361" data-lng="-97.716" data-price="459000" data-sqft="1522" data-status="for_sale" data-type="Single Family" data-zip="78758">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="459000" data-price-display="$459,000">$459,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1522">1,522</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1013">8100 Research Blvd, Austin, TX 78758</a></p>
<div class="nl-meta"><span data-days-on-nestly="11">11 days on Nestly</span></div>
<div class="nl-broker" data-agent="Morgan Lee" data-broker="North Nestly Homes">North Nestly Homes</div>
</div>
</article>, <article class="nl-card" data-baths="5.5" data-beds="5" data-city="Austin" data-days="55" data-hoa="120" data-home-id="nl-1014" data-lat="30.301" data-lng="-97.795" data-price="2150000" data-sqft="4820" data-status="for_sale" data-type="Single Family" data-zip="78746">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏰
            </div>
<div>
<p class="nl-price" data-price="2150000" data-price-display="$2,150,000">$2,150,000</p>
<p class="nl-facts"><strong data-beds="5">5</strong> bds | <strong data-baths="5.5">5.5</strong> ba | <strong data-sqft="4820">4,820</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1014">18 Westlake Dr, Austin, TX 78746</a></p>
<div class="nl-meta"><span data-days-on-nestly="55">55 days on Nestly</span> · HOA $120/mo</div>
<div class="nl-broker" data-agent="Jordan Hale" data-broker="Nestly Premier Realty">Nestly Premier Realty</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="3" data-city="Austin" data-days="8" data-hoa="95" data-home-id="nl-1015" data-lat="30.181" data-lng="-97.741" data-price="175000" data-sqft="1210" data-status="for_sale" data-type="Manufactured" data-zip="78744">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="Mobile home for sale">Mobile home for sale</span>
              🚐
            </div>
<div>
<p class="nl-price" data-price="175000" data-price-display="$175,000">$175,000</p>
<p class="nl-facts"><strong data-beds="3">3</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1210">1,210</strong> sqft | <span data-home-type="Manufactured">Manufactured</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1015">Lot 42 Pioneer Trails, Austin, TX 78744</a></p>
<div class="nl-meta"><span data-days-on-nestly="8">8 days on Nestly</span> · HOA $95/mo</div>
<div class="nl-broker" data-agent="Sam Ortiz" data-broker="Capitol Nest Group">Capitol Nest Group</div>
</div>
</article>, <article class="nl-card" data-baths="2" data-beds="4" data-city="Austin" data-days="14" data-hoa="0" data-home-id="nl-1016" data-lat="30.239" data-lng="-97.769" data-price="589000" data-sqft="1890" data-status="for_sale" data-type="Single Family" data-zip="78704">
<div aria-hidden="true" class="nl-card-img">
<span class="nl-badge sale" data-badge="House for sale">House for sale</span>
              🏠
            </div>
<div>
<p class="nl-price" data-price="589000" data-price-display="$589,000">$589,000</p>
<p class="nl-facts"><strong data-beds="4">4</strong> bds | <strong data-baths="2">2</strong> ba | <strong data-sqft="1890">1,890</strong> sqft | <span data-home-type="Single Family">Single Family</span></p>
<p class="nl-addr"><a href="/playground/nestly/home-nl-1016">1608 Southwood Rd, Austin, TX 78704</a></p>
<div class="nl-meta"><span data-days-on-nestly="14">14 days on Nestly</span></div>
<div class="nl-broker" data-agent="Riley Nguyen" data-broker="South Austin Estates">South Austin Estates</div>
</div>
</article>]

In [ ]:
import pandas as pd

all_prop_data = []

for i in card:
  price = i.find("p", class_="nl-price").text
  fact = i.find("p", class_="nl-facts").text
  meta = i.find("div", class_="nl-meta").text
  broker = i.find("div", class_="nl-broker").text
  #print(price, "|", fact, "|", meta, "|", broker)
  all_prop_data.append([price,fact,meta,broker])

df = pd.DataFrame(all_prop_data, columns=['price','fact','meta','broker'])

In [ ]:
display(df)

,price,fact,meta,broker
0,"$625,000","3 bds | 2 ba | 1,680 sqft | Single Family",6 days on Nestly,Nestly Premier Realty
1,"$419,000","2 bds | 2 ba | 1,045 sqft | Condo",12 days on Nestly · HOA $385/mo,Capitol Nest Group
2,"$875,000","4 bds | 3 ba | 2,450 sqft | Single Family",21 days on Nestly · HOA $45/mo,Nestly Premier Realty
3,"$512,000","3 bds | 2.5 ba | 1,720 sqft | Townhouse",4 days on Nestly · HOA $210/mo,Eastside Nestly
4,"$1,149,000","5 bds | 4 ba | 3,210 sqft | Single Family",18 days on Nestly,South Austin Estates
5,"$2,450/mo",2 bds | 2 ba | 980 sqft | Apartment,3 days on Nestly,Nestly Property Mgmt
6,"$389,000","3 bds | 2 ba | 1,410 sqft | Single Family",31 days on Nestly,Eastside Nestly
7,"$299,000",1 bds | 1 ba | 712 sqft | Condo,9 days on Nestly · HOA $295/mo,Capitol Nest Group
8,"$749,000","4 bds | 3 ba | 2,288 sqft | Single Family",15 days on Nestly · HOA $55/mo,Nestly Premier Realty
9,"$535,000","3 bds | 2 ba | 1,595 sqft | Single Family",27 days on Nestly,Nestly Premier Realty
10,"$3,200/mo","3 bds | 2 ba | 1,500 sqft | Single Family",2 days on Nestly,Nestly Property Mgmt
11,"$895,000","6 bds | 4 ba | 2,800 sqft | Multi Family",40 days on Nestly,Eastside Nestly
12,"$459,000","3 bds | 2 ba | 1,522 sqft | Single Family",11 days on Nestly,North Nestly Homes
13,"$2,150,000","5 bds | 5.5 ba | 4,820 sqft | Single Family",55 days on Nestly · HOA $120/mo,Nestly Premier Realty
14,"$175,000","3 bds | 2 ba | 1,210 sqft | Manufactured",8 days on Nestly · HOA $95/mo,Capitol Nest Group
15,"$589,000","4 bds | 2 ba | 1,890 sqft | Single Family",14 days on Nestly,South Austin Estates

In [ ]:
print(df["fact"].head())

0    3 bds | 2 ba | 1,680 sqft | Single Family
1            2 bds | 2 ba | 1,045 sqft | Condo
2    4 bds | 3 ba | 2,450 sqft | Single Family
3      3 bds | 2.5 ba | 1,720 sqft | Townhouse
4    5 bds | 4 ba | 3,210 sqft | Single Family
Name: fact, dtype: object

In [ ]:
df[["bedroom", "bathroom", "sqft", "property_type"]] = df["fact"].str.split("|", expand=True)

In [ ]:
display(df)

,price,fact,meta,broker,bedroom,bathroom,sqft,property_type
0,"$625,000","3 bds | 2 ba | 1,680 sqft | Single Family",6 days on Nestly,Nestly Premier Realty,3.0,2.0,"1,680 sqft",Single Family
1,"$419,000","2 bds | 2 ba | 1,045 sqft | Condo",12 days on Nestly · HOA $385/mo,Capitol Nest Group,2.0,2.0,"1,045 sqft",Condo
2,"$875,000","4 bds | 3 ba | 2,450 sqft | Single Family",21 days on Nestly · HOA $45/mo,Nestly Premier Realty,4.0,3.0,"2,450 sqft",Single Family
3,"$512,000","3 bds | 2.5 ba | 1,720 sqft | Townhouse",4 days on Nestly · HOA $210/mo,Eastside Nestly,3.0,2.5,"1,720 sqft",Townhouse
4,"$1,149,000","5 bds | 4 ba | 3,210 sqft | Single Family",18 days on Nestly,South Austin Estates,5.0,4.0,"3,210 sqft",Single Family
5,"$2,450/mo",2 bds | 2 ba | 980 sqft | Apartment,3 days on Nestly,Nestly Property Mgmt,2.0,2.0,980 sqft,Apartment
6,"$389,000","3 bds | 2 ba | 1,410 sqft | Single Family",31 days on Nestly,Eastside Nestly,3.0,2.0,"1,410 sqft",Single Family
7,"$299,000",1 bds | 1 ba | 712 sqft | Condo,9 days on Nestly · HOA $295/mo,Capitol Nest Group,1.0,1.0,712 sqft,Condo
8,"$749,000","4 bds | 3 ba | 2,288 sqft | Single Family",15 days on Nestly · HOA $55/mo,Nestly Premier Realty,4.0,3.0,"2,288 sqft",Single Family
9,"$535,000","3 bds | 2 ba | 1,595 sqft | Single Family",27 days on Nestly,Nestly Premier Realty,3.0,2.0,"1,595 sqft",Single Family
10,"$3,200/mo","3 bds | 2 ba | 1,500 sqft | Single Family",2 days on Nestly,Nestly Property Mgmt,3.0,2.0,"1,500 sqft",Single Family
11,"$895,000","6 bds | 4 ba | 2,800 sqft | Multi Family",40 days on Nestly,Eastside Nestly,6.0,4.0,"2,800 sqft",Multi Family
12,"$459,000","3 bds | 2 ba | 1,522 sqft | Single Family",11 days on Nestly,North Nestly Homes,3.0,2.0,"1,522 sqft",Single Family
13,"$2,150,000","5 bds | 5.5 ba | 4,820 sqft | Single Family",55 days on Nestly · HOA $120/mo,Nestly Premier Realty,5.0,5.5,"4,820 sqft",Single Family
14,"$175,000","3 bds | 2 ba | 1,210 sqft | Manufactured",8 days on Nestly · HOA $95/mo,Capitol Nest Group,3.0,2.0,"1,210 sqft",Manufactured
15,"$589,000","4 bds | 2 ba | 1,890 sqft | Single Family",14 days on Nestly,South Austin Estates,4.0,2.0,"1,890 sqft",Single Family

In [ ]:
df["sqft"] = (
    df["sqft"]
    .str.replace(" sqft", "")
    .str.replace(",", "")
    .astype(int)
)

In [ ]:
print(df["sqft"])

0     1680
1     1045
2     2450
3     1720
4     3210
5      980
6     1410
7      712
8     2288
9     1595
10    1500
11    2800
12    1522
13    4820
14    1210
15    1890
Name: sqft, dtype: int64

In [ ]:
print(df["price"].unique())

['$625,000' '$419,000' '$875,000' '$512,000' '$1,149,000' '$2,450/mo'
 '$389,000' '$299,000' '$749,000' '$535,000' '$3,200/mo' '$895,000'
 '$459,000' '$2,150,000' '$175,000' '$589,000']

In [ ]:
df["listing_type"] = df["price"].apply( lambda x: "Rent" if "/mo" in x else "Sale")

In [ ]:
print(df[["price", "listing_type"]])

         price listing_type
0     $625,000         Sale
1     $419,000         Sale
2     $875,000         Sale
3     $512,000         Sale
4   $1,149,000         Sale
5    $2,450/mo         Rent
6     $389,000         Sale
7     $299,000         Sale
8     $749,000         Sale
9     $535,000         Sale
10   $3,200/mo         Rent
11    $895,000         Sale
12    $459,000         Sale
13  $2,150,000         Sale
14    $175,000         Sale
15    $589,000         Sale

In [ ]:
df["price"] = df['price'].str.replace("$", '').str.replace(",", '').str.replace("/mo", '').str.strip().astype(int)

In [ ]:
display(df)

,price,fact,meta,broker,bedroom,bathroom,sqft,property_type,listing_type
0,625000.0,"3 bds | 2 ba | 1,680 sqft | Single Family",6 days on Nestly,Nestly Premier Realty,3.0,2.0,1680,Single Family,Sale
1,419000.0,"2 bds | 2 ba | 1,045 sqft | Condo",12 days on Nestly · HOA $385/mo,Capitol Nest Group,2.0,2.0,1045,Condo,Sale
2,875000.0,"4 bds | 3 ba | 2,450 sqft | Single Family",21 days on Nestly · HOA $45/mo,Nestly Premier Realty,4.0,3.0,2450,Single Family,Sale
3,512000.0,"3 bds | 2.5 ba | 1,720 sqft | Townhouse",4 days on Nestly · HOA $210/mo,Eastside Nestly,3.0,2.5,1720,Townhouse,Sale
4,1149000.0,"5 bds | 4 ba | 3,210 sqft | Single Family",18 days on Nestly,South Austin Estates,5.0,4.0,3210,Single Family,Sale
5,2450.0,2 bds | 2 ba | 980 sqft | Apartment,3 days on Nestly,Nestly Property Mgmt,2.0,2.0,980,Apartment,Rent
6,389000.0,"3 bds | 2 ba | 1,410 sqft | Single Family",31 days on Nestly,Eastside Nestly,3.0,2.0,1410,Single Family,Sale
7,299000.0,1 bds | 1 ba | 712 sqft | Condo,9 days on Nestly · HOA $295/mo,Capitol Nest Group,1.0,1.0,712,Condo,Sale
8,749000.0,"4 bds | 3 ba | 2,288 sqft | Single Family",15 days on Nestly · HOA $55/mo,Nestly Premier Realty,4.0,3.0,2288,Single Family,Sale
9,535000.0,"3 bds | 2 ba | 1,595 sqft | Single Family",27 days on Nestly,Nestly Premier Realty,3.0,2.0,1595,Single Family,Sale
10,3200.0,"3 bds | 2 ba | 1,500 sqft | Single Family",2 days on Nestly,Nestly Property Mgmt,3.0,2.0,1500,Single Family,Rent
11,895000.0,"6 bds | 4 ba | 2,800 sqft | Multi Family",40 days on Nestly,Eastside Nestly,6.0,4.0,2800,Multi Family,Sale
12,459000.0,"3 bds | 2 ba | 1,522 sqft | Single Family",11 days on Nestly,North Nestly Homes,3.0,2.0,1522,Single Family,Sale
13,2150000.0,"5 bds | 5.5 ba | 4,820 sqft | Single Family",55 days on Nestly · HOA $120/mo,Nestly Premier Realty,5.0,5.5,4820,Single Family,Sale
14,175000.0,"3 bds | 2 ba | 1,210 sqft | Manufactured",8 days on Nestly · HOA $95/mo,Capitol Nest Group,3.0,2.0,1210,Manufactured,Sale
15,589000.0,"4 bds | 2 ba | 1,890 sqft | Single Family",14 days on Nestly,South Austin Estates,4.0,2.0,1890,Single Family,Sale