<a href="https://colab.research.google.com/github/shubhkhandare/realestate-data-analysis/blob/main/HTMLwebscrap_BSoup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
html = """
<html>
<body>

<div class="property">
    <h2 class="property-name">3 BHK Flat</h2>
    <span class="location">Balewadi</span>
    <span class="budget">60 Lakh</span>
</div>

<div class="property">
    <h2 class="property-name">2 BHK Flat</h2>
    <span class="location">Baner</span>
    <span class="budget">45 Lakh</span>
</div>

<div class="property">
    <h2 class="property-name">4 BHK Villa</h2>
    <span class="location">Wakad</span>
    <span class="budget">1 Crore</span>
</div>

</body>
</html>
"""

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(html, 'html.parser')

###I need property name, location and budget for every listing.”

In [ ]:
result = soup.find_all("div", class_ = "property")

In [ ]:
for i  in result:
  property_name = i.find("h2", class_="property-name").text
  location = i.find("span", class_="location").text
  budget = i.find("span", class_="budget").text
  print(property_name, location, budget)

3 BHK Flat Balewadi 60 Lakh
2 BHK Flat Baner 45 Lakh
4 BHK Villa Wakad 1 Crore

In [ ]:
import pandas as pd

properties_data = []
for i in result:
    property_name = i.find("h2", class_="property-name").text
    location = i.find("span", class_="location").text
    budget = i.find("span", class_="budget").text
    properties_data.append([property_name, location, budget])

df_prop = pd.DataFrame(properties_data, columns= ['name', 'location', 'budget'])
display(df_prop)

          name  location   budget
0   3 BHK Flat  Balewadi  60 Lakh
1   2 BHK Flat     Baner  45 Lakh
2  4 BHK Villa     Wakad  1 Crore

In [ ]:
def converter(value):

  if isinstance(value, (int, float)):
      return value


  value = str(value).strip()

  if 'Crore' in value:
    number = float(value.replace('Crore', '').strip())
    return number * 10000000

  elif 'Lakh' in value:
    number1 = float(value.replace('Lakh', '').strip())
    return number1 * 100000
  else:
    try:
       return float(value)
    except ValueError:
       return None

In [ ]:
df_prop['budget'] = df_prop['budget'].apply(converter)

In [ ]:
df_prop.head()

          name  location      budget
0   3 BHK Flat  Balewadi   6000000.0
1   2 BHK Flat     Baner   4500000.0
2  4 BHK Villa     Wakad  10000000.0

In [ ]:
df_prop.drop_duplicates(subset= ['location', 'budget'])

          name  location      budget
0   3 BHK Flat  Balewadi   6000000.0
1   2 BHK Flat     Baner   4500000.0
2  4 BHK Villa     Wakad  10000000.0

##Now give me only properties where the budget is greater than ₹50 lakh, and show the result sorted from highest budget to lowest

In [ ]:
df_prop[df_prop['budget'] > 5000000].sort_values(by='budget', ascending=False)

          name  location      budget
2  4 BHK Villa     Wakad  10000000.0
0   3 BHK Flat  Balewadi   6000000.0

##save

In [ ]:
df_prop = df_prop.sort_values(by='budget', ascending=False)

In [ ]:
df_prop.to_csv("property_leads_by_BSoup.csv", index=False)